config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks", invitations: 'users/invitations',
    confirmations: 'users/confirmations' }
  root to: "posts#index"

  resources :categories, only: [:index, :new, :create, :destroy]
  resources :sources

  resources :topics, only: :show

  resources :posts, only: :show, constraints: ->(request) { request.protocol == "http://" }
  resources :posts, only: :index do
    scope module: :posts do
      resource :header, only: :show
      resources :comments, only: :index
      resources :reviews, only: [:index, :create, :destroy]
      resources :review_comments, only: [:create, :destroy]
      resource :vote, only: [:update, :destroy]
      resource :categories, only: :update
    end
  end

  resources :users, only: [:index, :update, :edit] do
    scope module: :users do
      resource :moderator_permissions, only: [:create, :destroy]
      resource :admin_permissions, only: [:create, :destroy]
    end
  end

  namespace :sources do
    resources :approve, only: [:update]
    resources :suggest, only: [:create, :new]
  end

  resources :feedbacks, only: [:create]
  get "contact_us", to: "feedbacks#new", as: :new_feedback

  get "terms_of_use", to: "static_pages#terms_of_use"
  get "about_us", to: "static_pages#about_us"
  get "qs_and_as", to: "static_pages#qs_and_as"

  namespace :api do
    resources :sources, only: [:update]
  end

  authenticated :user, ->(user) { user.role.admin? } do
    Sidekiq::Web.set :session_secret, Rails.application.secrets[:secret_key_base]
    mount Sidekiq::Web, at: '/sidekiq'
  end
end

app/helpers/layout_helper.rb
module LayoutHelper
  def post_header_base_link
    root_url(protocol: post_header_protocol)
  end

  private

  def post_header_protocol
    Rails.application.config_for(:external_site_embedding)["post_header_protocol"]
  end
end

app/views/layouts/_application_js.slim
javascript:
  var _rollbarConfig = {
    accessToken: "#{ENV['ROLLBAR_CLIENT_TOKEN']}",
    captureUncaught: true,
    captureUnhandledRejections: true,
    payload: {
      environment: "#{Rails.env.to_json}",
      person: "#{current_user ? current_user.email : 'guest'}"
    }
  };

app/views/layouts/application.html.slim
doctype html
html dir="rtl" lang="ar"
  head
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1.0"

    title == content_for?(:title) ? yield(:title) : t("site_title")

    = stylesheet_link_tag "application"
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tag
    = google_analytics_tag
    = favicon_link_tag "favicon.png"

  body
    #fb-root data=Rails.application.secrets.facebook.slice("app_id", "api_version", "locale")

    .top-navigation
      .top-navigation__menu
        .top-navigation__logo
          .top-navigation-logo
            = link_to root_path do
              = image_tag "header_logo.png",
                      class: "top-navigation-logo__picture",
                      srcset: "#{path_to_image('header_logo_2x.png')} 2x"
        = check_box_tag "menu_toggle", "", false, class: "top-navigation__menu-toggle-checkbox"
        = label_tag "menu_toggle", "", class: "top-navigation__menu-toggle"
        .top-navigation__menu-items
          ul.top-navigation__actions
            li = link_to t("menu.sources.name"), sources_path
            li = link_to t(".survey"), 'https://docs.google.com/forms/d/1uY8hR7916-p7yTGPZKQ8KW5iJArfSKVHcAGTf6OXF4o/viewform?ts=5b082a4d&edit_requested=true'
            - if user_signed_in? && current_user.admin?
              li= link_to t("menu.categories"), categories_path
              li= link_to t("menu.users.name"), users_path
            - if !user_signed_in? || current_user.member?
              li= link_to t(".contact_us"), new_feedback_path

          ul.top-navigation__actions
            - if user_signed_in?
              li= link_to t("menu.edit_profile"), edit_user_path(current_user)
              li= link_to t("devise.sign_out"), destroy_user_session_path, method: :delete
            - else
              li= link_to t("devise.log_in"), new_user_session_path

    .application-content
      == yield

    .footer
      .footer__links
        .footer__link= link_to t('.about_us'), about_us_path
        .footer__link= link_to t('.terms_of_use'), terms_of_use_path
        .footer__link= link_to t('.qs_and_as'), qs_and_as_path
        .footer__link= link_to t('.contact_us'), new_feedback_path
        .footer__social-links
          .footer__link
            = link_to android_link do
              = image_tag 'socials/android.svg', class: 'footer__social-icon'
              span.footer__social-name= t('layouts.footer.socials.android')
          .footer__link
            = link_to facebook_link do
              = image_tag 'socials/facebook.svg', class: 'footer__social-icon'
              span.footer__social-name= t('layouts.footer.socials.facebook')
          .footer__link
            = link_to twitter_link do
              = image_tag 'socials/twitter.svg', class: 'footer__social-icon'
              span.footer__social-name = t('layouts.footer.socials.twitter')

    .alerts.js-alerts
      .row
        .js-alerts__placeholder
      .alerts__queue
        - if flash[:notice].present?
          .js-alerts__queued-alert data-type="success" data-text=flash[:notice]
        - if flash[:alert].present?
          .js-alerts__queued-alert data-type="alert" data-text=flash[:alert]

    = render partial: 'layouts/application_js'

app/views/layouts/iframe_layout.html.slim
doctype html
html dir="rtl" lang="ar"
  head
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1.0"

    title == content_for?(:title) ? yield(:title) : t("site_title")

    = stylesheet_link_tag "application"
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = javascript_include_tag "https://unpkg.com/iframe-resizer@3.5.14/js/iframeResizer.min.js"
    = csrf_meta_tag

  body
    #fb-root data=Rails.application.secrets.facebook.slice("app_id", "api_version", "locale")

    == yield

    = render partial: 'layouts/application_js'

app/views/layouts/post_header_layout.html.slim
doctype html
html dir="rtl" lang="ar"
  head
    base[href=post_header_base_link]
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1.0"

    title == content_for?(:title) ? yield(:title) : t("site_title")

    = stylesheet_link_tag "application"
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tag
    = favicon_link_tag "favicon.png"

  body
    #fb-root data=Rails.application.secrets.facebook.slice("app_id", "api_version", "locale")

    == yield

    = render partial: 'layouts/application_js'

app/views/layouts/post_layout.html.slim
doctype html
html dir="rtl" lang="ar"
  head
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title == content_for?(:title) ? yield(:title) : t("site_title")
    = stylesheet_link_tag "application"
    = favicon_link_tag "favicon.png"
  body
    == yield